=== Sigsiu-NET/SobiPro/Component/branches/SobiPro-1.1/Site/lib/services/installers/schemas/template.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="template">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="id" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="[a-zA-Z0-9_-]{5,25}"/>
							<xs:whiteSpace value="preserve"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="authorName" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="authorEmail" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="authorUrl" type="xs:anyURI" minOccurs="0" maxOccurs="1"/>
				<xs:element name="copyright" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="license" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="creationDate" type="xs:date" minOccurs="1" maxOccurs="1"/>
				<xs:element name="version" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
				<xs:element name="previewImage" type="xs:string" minOccurs="0" maxOccurs="1"/>
				<xs:element name="files" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="file" maxOccurs="unbounded">
								 <xs:complexType>
								 	<xs:simpleContent>
								 		<xs:extension base="xs:string">								 
								 			<xs:attribute name="path" use="required" type="xs:string"/>
								 		</xs:extension>
								 	</xs:simpleContent>
								 </xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="exec" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="[a-zA-Z0-9]{3,50}\.php"/>
							<xs:whiteSpace value="preserve"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="requirements" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="core" type="requirement" minOccurs="0" maxOccurs="1"/>
							<xs:element name="application" type="requirement" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="field" type="requirement" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="php" type="requirement" minOccurs="0" maxOccurs="unbounded"/>
						</xs:choice>
					</xs:complexType>
				</xs:element>				
	            <xs:element name="install" minOccurs="0" maxOccurs="1">
	            	<xs:complexType>
	            		<xs:sequence>
	            			<xs:element name="section" minOccurs="0" maxOccurs="1">
	            				<xs:complexType>
	            					<xs:all>
	            						<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
	            						<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
	            						<xs:element name="nameField" type="xs:string" minOccurs="1" maxOccurs="1"/>
            							<xs:element name="showTopMenu" type="xs:boolean" default="true"/>
	            						<xs:element name="catsInLine" type="xs:int" minOccurs="1" maxOccurs="1" default="1"/>
            							<xs:element name="showCategoryDesc" type="xs:boolean" default="true"/>
            							<xs:element name="showCategoryMeta" type="xs:boolean" default="true"/>
            							<xs:element name="showCategorySubcats" type="xs:boolean" default="true"/>
        								<xs:element name="entriesInLine" type="xs:int" minOccurs="1" maxOccurs="1" default="1"/>	   
        								<xs:element name="entriesOnPage" type="xs:int" minOccurs="1" maxOccurs="1" default="5"/>
            							<xs:element name="showEntryMeta" type="xs:boolean" default="false"/>
            							<xs:element name="showEntryCategories" type="xs:boolean" default="true"/>
										<xs:element name="options" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:choice maxOccurs="unbounded">																		
													<xs:element name="option" maxOccurs="unbounded">
														 <xs:complexType>
														 	<xs:simpleContent>
														 		<xs:extension base="xs:string">								 
														 			<xs:attribute name="attribute" use="required" type="xs:string"/>
														 		</xs:extension>
														 	</xs:simpleContent>
														 </xs:complexType>
													</xs:element>
												</xs:choice>
											</xs:complexType>
										</xs:element>
										<xs:element name="fields" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="field" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="name" minOccurs="1" maxOccurs="1">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:pattern value="field_[a-zA-Z0-9_]{2,50}"/>
																			<xs:whiteSpace value="preserve"/>
																		</xs:restriction>
																	</xs:simpleType>																
																</xs:element>
																<xs:element name="label" minOccurs="1" maxOccurs="1">
																	<xs:complexType>
																		<xs:simpleContent>
																			<xs:extension base="xs:string">
																				<xs:attribute name="lang" use="optional" type="xs:string" default="en-GB"/>
																			</xs:extension>
																		</xs:simpleContent>
																	</xs:complexType>
																</xs:element>
																<xs:element name="type" type="xs:string" minOccurs="1" maxOccurs="1"/>
																<xs:element name="required" minOccurs="1" maxOccurs="1" type="xs:boolean"/>
																<xs:element name="showIn" minOccurs="1" maxOccurs="1" default="both">
						        									<xs:simpleType>
						        									  	<xs:restriction base="xs:string">
														    				<xs:enumeration value="both"/>
														    				<xs:enumeration value="details"/>
														    				<xs:enumeration value="vcard"/>
														    				<xs:enumeration value="hidden"/>
														  				</xs:restriction> 
														  			</xs:simpleType>          																							 	
																</xs:element>
																<xs:element name="options" minOccurs="0" maxOccurs="1">
																	<xs:complexType>
																		<xs:choice maxOccurs="unbounded">																		
																			<xs:element name="option" maxOccurs="unbounded">
																				 <xs:complexType>
																				 	<xs:simpleContent>
																				 		<xs:extension base="xs:string">								 
																				 			<xs:attribute name="attribute" use="required" type="xs:string"/>
																				 		</xs:extension>
																				 	</xs:simpleContent>
																				 </xs:complexType>
																			</xs:element>
																			<xs:element name="values" maxOccurs="unbounded">
																				<xs:complexType>
																					<xs:sequence>
																				 		<xs:element name="value" maxOccurs="unbounded">
																				 			<xs:complexType>
																				 				<xs:simpleContent> 
																				 					<xs:extension base="xs:string"> 
																				 						<xs:attribute name="name" use="optional" type="xs:string"/>
																				 						<xs:attribute name="group" use="optional" type="xs:string"/>
																				 						<xs:attribute name="lang" use="optional" type="xs:string"/>
																				 						<xs:attribute name="label" use="optional" type="xs:string"/>
																				 						<xs:attribute name="size" use="optional" type="xs:string"/>
																				 						<xs:attribute name="width" use="optional" type="xs:string"/>
																				 						<xs:attribute name="height" use="optional" type="xs:string"/>
																				 						<xs:attribute name="enabled" use="optional" type="xs:boolean"/>
																				 						<xs:attribute name="nid" use="optional" type="xs:string"/>
																				 						<xs:attribute name="type" use="optional" type="xs:string"/>
																				 						<xs:attribute name="position" use="optional" type="xs:int"/>
																				 						<xs:attribute name="params" use="optional" type="xs:string"/>
																				 						<xs:anyAttribute/>
																				 					</xs:extension>
																				 				</xs:simpleContent>
																				 			</xs:complexType>
																				 		</xs:element>
																				 	</xs:sequence>
																				 	<xs:attribute name="attribute" use="required" type="xs:string"/>
																				 </xs:complexType>
																			</xs:element>																		
																		</xs:choice>
																	</xs:complexType>
																</xs:element>						
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>		
										<xs:element name="categories" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="category" maxOccurs="unbounded">	
														<xs:complexType>
															<xs:complexContent>
																<xs:extension base="category"/>
															</xs:complexContent>
														</xs:complexType>						
													</xs:element>												
												</xs:sequence>
											</xs:complexType>
										</xs:element>				
	            					</xs:all>
	            				</xs:complexType>
	            			</xs:element>
	            		</xs:sequence>
	            	</xs:complexType>
	            </xs:element>
	        </xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="category">
		<xs:sequence>
			<xs:element name="name" minOccurs="1" maxOccurs="1">
				 <xs:simpleType>
				    <xs:restriction base="xs:string">
				      <xs:minLength value="2"/>
				      <xs:maxLength value="100"/>
				    </xs:restriction>
				  </xs:simpleType>			
			</xs:element>
			<xs:element name="introtext" minOccurs="0" maxOccurs="1" type="xs:string"/>
			<xs:element name="description" minOccurs="0" maxOccurs="1" type="xs:string"/>
			<xs:element name="icon" minOccurs="0" maxOccurs="1" type="xs:string"/>
			<xs:element name="options" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:choice maxOccurs="unbounded">																		
						<xs:element name="option" maxOccurs="unbounded">
							 <xs:complexType>
							 	<xs:simpleContent>
							 		<xs:extension base="xs:string">								 
							 			<xs:attribute name="attribute" use="required" type="xs:string"/>
							 		</xs:extension>
							 	</xs:simpleContent>
							 </xs:complexType>
						</xs:element>
					</xs:choice>
				</xs:complexType>
			</xs:element>			
			<xs:element name="childs" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="category" maxOccurs="unbounded">	
							<xs:complexType>
								<xs:complexContent>
									<xs:extension base="category"/>
								</xs:complexContent>
							</xs:complexType>						
						</xs:element>
					</xs:sequence>
				</xs:complexType>				
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="requirement" mixed="true">
		<xs:attribute name="version" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="(\d+\.)?(\d+\.)?(\d+)?(\.)?(\d+)?"/>						
					<xs:whiteSpace value="preserve"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="type" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="function|class"/>						
					<xs:whiteSpace value="preserve"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== Sigsiu-NET/SobiPro/Component/branches/SobiPro-1.1/Site/usr/templates/default/template.xml
<?xml version="1.0" encoding="UTF-8"?>
<template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="https://xml.sigsiu.net/SobiPro/template.xsd">
	<name>Default SobiPro Template</name>
	<id>default_template</id>
	<authorName>Sigrid Suski and Radek Suski</authorName>
	<authorEmail>sobi[at]sigsiu.net</authorEmail>
	<authorUrl>http://www.Sigsiu.NET</authorUrl>
	<copyright>Copyright (C) 2006-2013 Sigsiu.NET GmbH</copyright>
	<license>GNU General Public License</license>
	<creationDate>2013-01-01</creationDate>
	<version>2.0</version>
	<description>
		Default SobiPro Template for SobiPro 1.1
    </description>
	<files>
		<file path="category/view.xsl">
			Default category view template with top menu, navigation, entries and categories.
		</file>
		<file path="common/alphamenu.xsl">
			Template for the alpha menu. Fields chooser and calls the alpha index (letters) template.
		</file>
        <file path="common/alphindex.xsl">
            Template for the alpha index (letters) only.
        </file>
		<file path="common/catchooser.xsl">
			Sub-Template for the category chooser for the edit entry form.
		</file>
        <file path="common/categories.xsl">
            Template for the categories list (categoriesLoop). Calls the template for a single category.
        </file>
		<file path="common/category.xsl">
			Template for a single category in the categories list.
		</file>
		<file path="common/entries.xsl">
			Template to display all entries (entriesLoop) within a category or the search function. Build the structure of all entries and calls the "vCard" template while displaying single entry.
		</file>
		<file path="common/manage.xsl">
			Displays the managing functions like edit entry, approve aso, within an entry.
		</file>
        <file path="common/messages.xsl">
            Displays the message bar.
        </file>
		<file path="common/navigation.xsl">
			Template for the site navigation.
		</file>
		<file path="common/topmenu.xsl">
			Template for the top menu.
		</file>
		<file path="common/vcard.xsl">
			Template to display single entry within a category or the search function.
		</file>
		<file path="css/default.css">
			Default CSS file.
		</file>
        <file path="css/default.less">
            Less file for the default CSS file in case you prefer using Less.
        </file>
		<file path="css/edit.css">
			CSS file with extra styles for the add/edit entry page.
		</file>
        <file path="css/edit.less">
            Less file for the add/edit entry CSS file in case you prefer using Less.
        </file>
		<file path="css/search.css">
			CSS file with extra styles for the search function.
		</file>
        <file path="css/search.less">
            Less file for the search CSS file in case you prefer using Less.
        </file>
		<file path="entry/details.xsl">
			Template for the entry details view page.
		</file>
		<file path="entry/edit.xsl">
			Template for the add/edit entry page.
		</file>
		<file path="feeds/rss.xsl">
			Template for Atom/RSS feeds.
		</file>
		<file path="js/alpha.js">
			JavaScript functions for the alpha menu.
		</file>
		<file path="js/autosuggest.js">
            JavaScript functions for the auto-suggest feature used in search and add/edit entry page.
		</file>
		<file path="js/search.js">
			JavaScript functions for the search page.
		</file>
		<file path="listing/alpha.xsl">
			Alpha listings template.
		</file>
		<file path="payment/payment.xsl">
			Payment page after an entry has been added.
		</file>
        <file path="payment/list.xsl">
            List of payments on the payment page.
        </file>
		<file path="payment/submit.xsl">
			Template for the preview of the payment.
		</file>
		<file path="search/view.xsl">
			Template for the search function.
		</file>
		<file path="section/view.xsl">
			Template for the section main view.
		</file>
		<file path="template.php">
			PHP file with additional functions to use within templates.
		</file>
        <file path="translation.xml">
            Translation file for texts in templates.
        </file>
        <file path="config.ini">
            Main template configuration file.
        </file>
	</files>
</template>

=== Sigsiu-NET/SobiPro/Component/branches/SobiPro-1.1/Site/usr/templates/front/template.xml
<?xml version="1.0" encoding="UTF-8"?>
<template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="https://xml.sigsiu.net/SobiPro/template.xsd">
	<name>Default SobiPro Template</name>
	<id>front</id>
	<authorName>Sigrid Suski and Radek Suski</authorName>
	<authorEmail>sobi[at]sigsiu.net</authorEmail>
	<authorUrl>http://www.Sigsiu.NET</authorUrl>
	<copyright>Copyright (C) 2009-2010 Sigsiu.NET</copyright>
	<license>GNU General Public License</license>
	<creationDate>2010-01-01</creationDate>
	<version>1.0</version>
	<description>
		Default SobiPro Template for the SobiPro component frontpage
	</description>
	<files>
		<file path="default.xsl">
			Template for the list of all sections 
		</file>
		<file path="default.php">
			Template for the list of all sections in PHP format - not used at the moment
		</file>
	</files>
	<install />
</template>

=== Sigsiu-NET/SobiPro/Site/usr/templates/b3-default3/template.xml
<?xml version="1.0" encoding="UTF-8"?>
<template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://xml.sigsiu.net/SobiPro/template.xsd">
	<name>B3-Default Template V4</name>
	<id>b3-default3</id>
	<authorName>Sigrid Suski and Radek Suski</authorName>
	<authorEmail>sobi[at]sigsiu.net</authorEmail>
	<authorUrl>http://www.Sigsiu.NET</authorUrl>
	<copyright>Copyright (C) 2006-2017 Sigsiu.NET GmbH</copyright>
	<license>GNU General Public License</license>
	<creationDate>2017-06-22</creationDate>
	<version>4.0</version>
	<description>Default Template for SobiPro 1.4+ with Bootstrap 3 support.
	This template makes use of Bootstrap 3 and Font Awesome 3 elements and styles.</description>
	<files>
		<file path="category/view.xsl">
			Default category view template with top menu, navigation, entries and categories.
		</file>
		<file path="common/alphamenu.xsl">
			Template for the alpha menu. Fields chooser and calls the alpha index (letters) template.
		</file>
        <file path="common/alphaindex.xsl">
            Template for the alpha index (letters) only.
        </file>
        <file path="common/categories.xsl">
            Template for the categories list (categoriesLoop). Calls the template for a single category.
        </file>
		<file path="common/category.xsl">
			Template for a single category in the categories list.
		</file>
		<file path="common/editfields.xsl">
			Template to output one field in entry form. Called from default loop in edit.xsl.
		</file>
		<file path="common/entries.xsl">
			Template to display all entries (entriesLoop) within a category or the search function. Build the structure of all entries and calls the "vCard" template while displaying single entry.
		</file>
		<file path="common/font.xsl">
			Template to load Google fonts.
		</file>
		<file path="common/manage.xsl">
			Displays the managing functions like edit entry, approve aso, within an entry.
		</file>
        <file path="common/messages.xsl">
            Displays the message bar.
        </file>
		<file path="common/navigation.xsl">
			Template for the site navigation.
		</file>
		<file path="common/searchfields.xsl">
			Template to output one field in the search. Called from default loop.
		</file>
		<file path="common/showfields.xsl">
			Template to output one field in vCard and details view. Called from default loop.
		</file>
		<file path="common/topmenu.xsl">
			Template for the top menu.
		</file>
		<file path="common/vcard.xsl">
			Template to display single entry within a category, any listing view or the search function.
		</file>
		<file path="css/tmpl/jbootstrap.css">
			CSS classes to restore changes made by Joomla Bootstrap 2 template.
		</file>
		<file path="css/tmpl/joostrap.css">
			CSS classes to restore changes made by Joostrap templates.
		</file>
		<file path="css/default.css">
			Default CSS file. Your own CSS changes goes in here.
		</file>
        <file path="css/default.less">
            LESS file for the default CSS file. Your own CSS changes goes in here.
        </file>
        <file path="css/theme.css">
            The theme CSS file. Automatically generated!
        </file>
        <file path="css/theme.less">
            LESS file for the theme CSS file.
        </file>
		<file path="entry/details.xsl">
			Template for the entry details view page.
		</file>
		<file path="entry/details.ini">
			Configuration file to load JS files in details view.
		</file>
		<file path="entry/edit.xsl">
			Template for the add/edit entry page.
		</file>
		<file path="entry/edit.ini">
			Configuration file to load JS files in entry form.
		</file>
		<file path="entry/edit.json">
			Configuration file for the entry form. Automatically generated!
		</file>
		<file path="feeds/rss.xsl">
			Template for Atom/RSS feeds.
		</file>
		<file path="feeds/rss.ini">
			Configuration file for RSS feeds.
		</file>
		<file path="feeds/rss.json">
			Configuration file for RSS feeds. Automatically generated!
		</file>
		<file path="js/alpha.js">
			JavaScript functions for the alpha menu.
		</file>
		<file path="js/autosuggest.js">
            JavaScript functions for the auto-suggest feature used in search and entry form.
		</file>
		<file path="js/details.js">
			JavaScript functions for the details view.
		</file>
		<file path="js/navigation.js">
			JavaScript functions for AJAX navigation.
		</file>
		<file path="js/search.js">
			JavaScript functions for the search form.
		</file>
		<file path="listing/alpha.xsl">
			Alpha listings template.
		</file>
		<file path="listing/date.xsl">
			Date listings template.
		</file>
		<file path="listing/user.xsl">
			User listings template.
		</file>
		<file path="payment/list.xsl">
			List of payments on the payment page.
		</file>
		<file path="payment/payment.xsl">
			Payment page after an entry has been added.
		</file>
		<file path="payment/submit.xsl">
			Template for the preview of the payment.
		</file>
		<file path="search/view.xsl">
			Template for the search form.
		</file>
		<file path="search/search.ini">
			Configuration file to load JS files in search form.
		</file>
		<file path="section/view.xsl">
			Template for the section main view.
		</file>
		<file path="section/ajax.xsl">
			Template for AJAX navigation.
		</file>
		<file path="section/ajax.ini">
			Configuration file for AJAX navigation.
		</file>
        <file path="themes/cornfield.less">
            Cornfield color theme (yellow/orange/brown).
        </file>
        <file path="themes/cornflower.less">
            Cornflower color theme (blue).
        </file>
        <file path="themes/malva.less">
            Malva color theme (violett).
        </file>
        <file path="themes/meadow.less">
            Meadow color theme (green).
        </file>
        <file path="themes/poppyseed.less">
            Poppyseed color theme (shades of grey).
        </file>
        <file path="themes/roses.less">
            Roses color theme (red/rose).
        </file>
        <file path="themes/sobipro.less">
            SobiPro color theme (SobiPro colors; default).
        </file>
		<file path="themes/terra.less">
			Terra color theme (brown).
		</file>
		<file path="themes/waterfall.less">
			Waterfall color theme (aquamarine).
		</file>
		<file path="template.php">
			PHP file with additional functions to use within templates.
		</file>
        <file path="translation.xml">
            Translation file for texts in templates.
        </file>
        <file path="config.ini">
            Main template configuration file.
        </file>
        <file path="config.xml">
            Template settings file.
        </file>
		<file path="config.json">
			Template settings configuration file. Automatically generated!
		</file>
	</files>
</template>

=== Sigsiu-NET/SobiPro/Site/usr/templates/default3/template.xml
<?xml version="1.0" encoding="UTF-8"?>
<template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://xml.sigsiu.net/SobiPro/template.xsd">
	<name>Default SobiPro Template V3</name>
	<id>default3</id>
	<authorName>Sigrid Suski and Radek Suski</authorName>
	<authorEmail>sobi[at]sigsiu.net</authorEmail>
	<authorUrl>http://www.Sigsiu.NET</authorUrl>
	<copyright>Copyright (C) 2006-2015 Sigsiu.NET GmbH</copyright>
	<license>GNU General Public License</license>
	<creationDate>2015-08-28</creationDate>
	<version>3.0</version>
	<description>Default SobiPro Template for SobiPro since 1.2</description>
	<files>
		<file path="category/view.xsl">
			Default category view template with top menu, navigation, entries and categories.
		</file>
		<file path="common/alphamenu.xsl">
			Template for the alpha menu. Fields chooser and calls the alpha index (letters) template.
		</file>
        <file path="common/alphaindex.xsl">
            Template for the alpha index (letters) only.
        </file>
        <file path="common/categories.xsl">
            Template for the categories list (categoriesLoop). Calls the template for a single category.
        </file>
		<file path="common/category.xsl">
			Template for a single category in the categories list.
		</file>
		<file path="common/entries.xsl">
			Template to display all entries (entriesLoop) within a category or the search function. Build the structure of all entries and calls the "vCard" template while displaying single entry.
		</file>
		<file path="common/manage.xsl">
			Displays the managing functions like edit entry, approve aso, within an entry.
		</file>
        <file path="common/messages.xsl">
            Displays the message bar.
        </file>
		<file path="common/navigation.xsl">
			Template for the site navigation.
		</file>
		<file path="common/topmenu.xsl">
			Template for the top menu.
		</file>
		<file path="common/vcard.xsl">
			Template to display single entry within a category or the search function.
		</file>
		<file path="css/default.css">
			Default CSS file.
		</file>
        <file path="css/default.less">
            LESS file for the default CSS file.
        </file>
		<file path="entry/details.xsl">
			Template for the entry details view page.
		</file>
		<file path="entry/edit.xsl">
			Template for the add/edit entry page.
		</file>
		<file path="feeds/rss.xsl">
			Template for Atom/RSS feeds.
		</file>
		<file path="js/alpha.js">
			JavaScript functions for the alpha menu.
		</file>
		<file path="js/autosuggest.js">
            JavaScript functions for the auto-suggest feature used in search and add/edit entry page.
		</file>
		<file path="js/search.js">
			JavaScript functions for the search page.
		</file>
		<file path="listing/alpha.xsl">
			Alpha listings template.
		</file>
		<file path="payment/payment.xsl">
			Payment page after an entry has been added.
		</file>
        <file path="payment/list.xsl">
            List of payments on the payment page.
        </file>
		<file path="payment/submit.xsl">
			Template for the preview of the payment.
		</file>
		<file path="search/view.xsl">
			Template for the search function.
		</file>
		<file path="section/view.xsl">
			Template for the section main view.
		</file>
        <file path="themes/blackwidow.less">
            Blackwidow color theme (black; light on dark).
        </file>
        <file path="themes/cornfield.less">
            Cornfield color theme (yellow/orange/brown).
        </file>
        <file path="themes/cornflower.less">
            Cornflower color theme (blue).
        </file>
        <file path="themes/malva.less">
            Malva color theme (violett).
        </file>
        <file path="themes/meadow.less">
            Meadow color theme (green).
        </file>
        <file path="themes/poppyseed.less">
            Poppyseed color theme (shades of grey).
        </file>
        <file path="themes/roses.less">
            Roses color theme (red/rose).
        </file>
        <file path="themes/sobipro.less">
            SobiPro color theme (SobiPro colors; default).
        </file>
		<file path="template.php">
			PHP file with additional functions to use within templates.
		</file>
        <file path="translation.xml">
            Translation file for texts in templates.
        </file>
        <file path="config.ini">
            Main template configuration file.
        </file>
	</files>
</template>

=== Sigsiu-NET/SobiPro/Site/usr/templates/storage/template.xml
<?xml version="1.0" encoding="UTF-8"?>
<template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="https://xml.sigsiu.net/SobiPro/template.xsd">
	<name>SobiPro Template Storage</name>
	<id>storage</id>
	<authorName>Sigrid Suski and Radek Suski</authorName>
	<authorEmail>sobi[at]sigsiu.net</authorEmail>
	<authorUrl>http://www.Sigsiu.NET</authorUrl>
	<copyright>Copyright (C) 2006-2016 Sigsiu.NET GmbH</copyright>
	<license>GNU General Public License</license>
	<creationDate>2016-08-31</creationDate>
	<version>1.0</version>
	<description>
		Template Storage. Stores the template files installed with applications.
	</description>
	<files />
	<install />
</template>
